
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - garage-net
    environment:
      FLASK_ENV: development # Enable development mode
      FLASK_DEBUG: 1         # Enable debug mode with reloader

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - garage-net
    environment:
      - CHOKIDAR_USEPOLLING=true # For hot-reloading the front end

networks:
  garage-net:
    driver: bridge