name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run basic tests
        run: |
          python -m unittest discover app

      - name: Build Docker image
        run: |
          docker build -t devops-app .
